### ISSUE TITLE
Plugin not receiving action responses when performing crafting actions

### ISSUE THREAD

**Issue by Junie-774** [Junie-774/CraftingList#28]
Plugin does not detect when crafting responses come in from the server -- likely a broken sig

**Comment by Junie-774** [comment]
tentatively fixed, will close if nobody comes in saying its still broke

**Comment by OtisOathkeeper** [comment]
Hey Junie, I haven't been using the plugin for a while now pending dawntrail's release and waiting as plugins get updated and re-enabled. I've found that crafts are unable to complete, it performs the first action of the macro and then the plugin tries to repeat the action. I've found that this happens chiefly when a macro begins with Reflect. 

Reflect did update in dawntrail but it did not change significantly, just a buff to its initial quality when you use it. 

![ffxiv_dx11_G0KzhSt4KM](https://github.com/user-attachments/assets/b2b489c3-63e3-4b5a-a017-f771a0ff8476)

I did experience a crash earlier when I was quick synthing gemstones...hasn't happened since though.
