### ISSUE TITLE
[Feature Req] Option to use Medicine/Draughts

### ISSUE THREAD

**Issue by redeven** [Junie-774/CraftingList#6]
As high-end recipes tend to be fairly difficult and require draughts (at least for mid-tier meld sets), it would be great to have an option for using draughts similar to foods (with the expected duration math to maximize buff utility and getting up to refresh after it runs out).

**Comment by Junie-774** [comment]
This is a good feature, thank you for bringing it up!

Right now, I'm working on reworking food selection so that the options for each Macro includes what food it needs to complete successfully. Meaning you'd select your food as part of your macro, rather than with the entry in the Crafting List.

Adding pots as an option with each macro would be a simple enough addition to that, I'm not going to bother adding it as a feature like how food works now when what i'm currently working on will break it, but it'll be included as part of that update! I'll close this issue when that update comes out
